version: "3.9"

services:
  dev:
    init: true
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
