version: "3.9"

services:
  dev:
    init: true
    build:
      args:
        DOCKER_BUILDKIT: 1
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - "5432:5432"
